### ISSUE TITLE
Trim whitespace in quickstart

### ISSUE THREAD

**Issue by philipws** [aws-samples/document-translation#18]
The quickstart can produce variables with training whitespace, as they are quoted strings, resulting in errors at deployment.

**Comment by Psychodahlia** [comment]
Hi @philipws, I found this through the 'good first issue' label and would love to help out. I was looking through the quick-start.md. Do you have an example or a line number I could look at to recreate the issue? Or am I looking in the wrong place?

Thank you!

**Comment by philipws** [comment]
Hey @Psychodahlia great that you want to contribute. Apologies, I was stuck on a train, so had some free time to resolve this myself. You can see the changes here https://github.com/aws-samples/document-translation/commit/f7edb4a66a221f2980e338593a14162b2de6fd92

If there are other areas you think could be improved I'm more than happy to guide on that.
