### ISSUE TITLE
Download button links to single file despite multiple languages selected for translation

### ISSUE THREAD

**Issue by bzahniser** [aws-samples/document-translation#21]
Uploading a document for a new translation, selecting multiple languages.  The Download button only links to one of the selected languages.  Interface should show multiple download buttons, one for each language, or download a Zip file of all translations.

**Comment by philipws** [comment]
Hey @bzahniser thanks for exploring the app. The default action should be to download all files with the single download button. Can you please ensure that pop-ups are not blocked by your browser and try again?

For Chrome: https://support.google.com/chrome/answer/95472 
For Firefox:

![image](https://github.com/aws-samples/document-translation/assets/99793964/2ccf546f-f97c-4bc7-94ef-7a6990a5ff2b)

The reason for this is that each file is a separate object within S3 and get a pre-signed URL for download. The web client is opening each of those pre-signed URLs to grab the file. New tabs will appear temporarily and self close.

**Comment by bzahniser** [comment]
Interesting behavior here – I checked this and it is indeed the popup blocker.  I didn’t catch this the first time as it would popup my finder to save 1 of my 3 translations with no warnings, but hidden behind that was a popup blocker alert for the other 2 files.

Had no files downloaded I would have initially looked for popup blocker alert, so I was thrown off by the fact that 1 of the 3 translated files downloaded fine.  Perhaps a note in the README to check for this would be a good addition.

Thanks for the quick response!

Bert

From: philipws ***@***.***>
Reply-To: aws-samples/document-translation ***@***.***>
Date: Wednesday, September 20, 2023 at 6:21 AM
To: aws-samples/document-translation ***@***.***>
Cc: "Zahniser, Bert" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-samples/document-translation] Download button links to single file despite multiple languages selected for translation (Issue #21)


Hey @bzahniser<https://github.com/bzahniser> thanks for exploring the app. The default action should be to download all files with the single download button. Can you please ensure that pop-ups are not blocked by your browser and try again?

For Chrome: https://support.google.com/chrome/answer/95472
For Firefox:

[Image removed by sender. image]<https://user-images.githubusercontent.com/99793964/269250498-2ccf546f-f97c-4bc7-94ef-7a6990a5ff2b.png>

The reason for this is that each file is a separate object within S3 and get a pre-signed URL for download. The web client is opening each of those pre-signed URLs to grab the file. New tabs will appear temporarily and self close.

**Comment by philipws** [comment]
@bzahniser No worries, happy to help. Thanks for confirming it worked.

**Comment by scmdavid** [comment]
For Egde, we also need to disable using Office viewer option 

1.	Open the Edge browser and click on the three-dotted icon.
2.	On the left, click on Downloads.
3.	In the right panel, turn off (disable) the Quickly open Office files on the web using Office viewer option.

**Comment by philipws** [comment]
https://github.com/aws-amplify/amplify-js/issues/13326
