### ISSUE TITLE
Enhancement Request: Add Custom Terminologies drop down on Web UI new translation page

### ISSUE THREAD

**Issue by bzahniser** [aws-samples/document-translation#26]
Add a dropdown to the web UI to show custom terminologies associated with the account and giving the user the optional ability to select one for the job.  A given account may have multiple custom terminology files based on the business unit or category of document being translated.

**Comment by philipws** [comment]
Hey @bzahniser thank you for the input.

Today the custom terminology matches the target language, if one exists, it will use it.

I'm not sure how the UI would handle having a dropdown for terminologies as they are per language. Every one of the 75 would have to have a dropdown and then be selected by the user. If a terminology is requested that doesn't exist, the job request will fail. Can you see a simpler way for the UI? 

The same would apply for parallel data in active translations if it gets added, making 2 dropdowns per language.

**Comment by bzahniser** [comment]
Hi Philip,

My understanding is custom terminology files support multiple languages.  My thinking was a customer might have different terminology CSV files they maintain for different purposes.  Perhaps they are translating technical manuals, or HR documents, or legal documents, and have different custom terminology for each.

When I go through the Amazon Translate Console, if I have uploaded multiple custom terminology files, I see a drop down where I can select which one I want to use for the job.  I was thinking a similar drop down could be used from this UI.  I see this drop down in both the Real-time page and create job in the Batch Translation page.

***@***.***

Looking at the API reference, there is a ListTerminologies<https://docs.aws.amazon.com/translate/latest/APIReference/API_ListTerminologies.html> which I suspect would return the contents for the dropdown.
--
bertzahniser
Principal Solutions Architect
Amazon Web Services
***@***.******@***.***>
Phone: 609.760.0615
CISSP, CCSP, AWS Certified<https://www.youracclaim.com/users/bert-zahniser/badges>
Connect with me on  [In-2C-21px-R] <https://www.linkedin.com/in/bertzahniser/>

From: philipws ***@***.***>
Reply-To: aws-samples/document-translation ***@***.***>
Date: Tuesday, November 7, 2023 at 10:24 AM
To: aws-samples/document-translation ***@***.***>
Cc: "Zahniser, Bert" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-samples/document-translation] Enhancement Request: Add Custom Terminologies drop down on Web UI new translation page (Issue #26)


Hey @bzahniser<https://github.com/bzahniser> thank you for the input.

Today the custom terminology matches the target language, if one exists, it will use it.

I'm not sure how the UI would handle having a dropdown for terminologies as they are per language. Every one of the 75 would have to have a dropdown and then be selected by the user. If a terminology is requested that doesn't exist, the job request will fail. Can you see a simpler way for the UI?

The same would apply for parallel data in active translations if it gets added, making 2 dropdowns per language.

**Comment by philipws** [comment]
Currently I don't see a big push towards per language and per translation CT. Additionally having this user configurable would change the workflow to make the user do more steps are job creation. With that I don't see this issue being worked on currently. If someone wishes to work on this and can share how they would make it seamless to current users I am more than happy to work with you and try get that work merged upstream.
