### ISSUE TITLE
"sourceGitRepo is required"

### ISSUE THREAD

**Issue by scmdavid** [aws-samples/document-translation#28]
I am  using v1.1.8 and going to use CodeCommit as the repo. 

The [doc](https://aws-samples.github.io/document-translation/docs/installation/deploy.html#deploy-the-pipeline) said, `sourceGitService` and `sourceGitRepo` are for GitHub only. However, when they were not set, I got the error

`/home/cloudshell-user/document-translation/infrastructure/lib/pipeline-stack.ts:100
throw new Error("sourceGitRepo is required");`

What should I set  sourceGitRepo for CodeCommit?

**Comment by philipws** [comment]
Hey @scmdavid you are correct, the documentation needs an update. It can be whatever value you want the repository name to be. The default I've used is `document-translation`.

This is what the quick-start generator uses. 

```sh
export sourceGitRepo="document-translation" # Set repo name
```

**Comment by philipws** [comment]
Thank you for reporting this. The docs have been updated now, which closes this issue. If you still have any problems please reopen with comment.
