### ISSUE TITLE
DocTran-main-app stack was rolled back

### ISSUE THREAD

**Issue by scmdavid** [aws-samples/document-translation#29]
Hi,

When I deployed the stack with `cdk deploy`, it failed and rolled back, this was likely cause:
```
CREATE_FAILED
basetranslatefeatTranslationPiimacieCustomDataIdentifier

Resource handler returned message: "Error occurred during operation 'AWS::Macie::CustomDataIdentifier'." (RequestToken: xxxxxx-49e7-16b6-cdfd-xxxxx, HandlerErrorCode: GeneralServiceException)
```
I tied opt in/out the translationPii, but same problem.

**Comment by scmdavid** [comment]
Hi @philipws , thanks! it worked. Also, thanks for your detailed release notes. I think I can also follow it when I need to setup the environment variables for the custom domain later without doing the deployment again.

**Comment by philipws** [comment]
@scmdavid thank you for checking the project out and your patience in the issues. I really believe it can have a great positive impact in peoples lives. The more the better.
