### ISSUE TITLE
Clean-up the environment (question/enhancement)

### ISSUE THREAD

**Issue by scmdavid** [aws-samples/document-translation#30]
We may migrate the app to a different AWS account; how can I completely remove all the resources created by this app?

During my tests, I had to do `cdk deploy` a few times. Each time, I deleted the two stacks: DocTran-main-app and DocTran-main-pipeline. However, at least the following resources remained: S3 buckets, user pool at IAM, and log groups in CloudWatch.

At the very minimum, I had to remove the log groups before doing a fresh `cdk deploy`; otherwise, the deployment would fail due to the existing log group.

**Comment by philipws** [comment]
The CloudWatch logs specifically should apply to these 2 flags. E.g. for the StepFunctions the below is configured. This takes a removal policy passed in as a property and applies it to the StepFunction log configuration. 

https://github.com/aws-samples/document-translation/blob/8565d23787be5948aca19908dbfbc7d350380478/infrastructure/lib/components/dt_stepfunction.ts#L37

**Comment by scmdavid** [comment]
Thanks
