### ISSUE TITLE
Document Translate only downloads first translation if multiple languages are selected

### ISSUE THREAD

**Issue by MarkVanKerro** [aws-samples/document-translation#45]
Hope its ok to post this.

you are able to select multiple languages for document translation and this is shown in the history page after submission, however when you download the document(s) it only provides the translation for one of the languages selected.

**Comment by philipws** [comment]
Hey @MarkVanKerro thanks for reaching out. This is a browser config which can be easily sorted. Please see #21

**Comment by MarkVanKerro** [comment]
Local Government - Official - CCC and PCC

Thank You, Pop-up blocker (allow) resolved the issue.


Mark Van-Kerro​ | Principal Technical Specialist

Cambridgeshire County Council

Peterborough City Council​

m: +44 7920 160 168​

t: +44 1733 317 922

Chat with me on ***@***.***> [cid:3db6c2e9-4932-4fad-b406-5b06585e36cf]





IT & Digital Services




Local Government - Official - CCC and PCC

________________________________
