### ISSUE TITLE
DocTran-main-pipeline Deployment fails at DocTran-appStack stage (deployWebsiteToS3)

### ISSUE THREAD

**Issue by mcalligator** [aws-samples/document-translation#66]
I deployed a new instance of `document-translation` today, and it unfortunately failed at the final hurdle: deploying the app's website to S3 and CloudFront.

I've included the relevant lines from CodePipeline's log below - the key message appears to be this:
`Module not found: Error: Can't resolve '../../../graphql/subscriptions' in '/codebuild/output/src27274233/src/website/src/page/readable/hooks'`.

I checked the zipped artefact stored in the doctran pipeline bucket, and it correctly didn't include that file.  Why correctly?  Because `Readable` is not specified in the configuration for what's deployed: I want to use Translate only.  I checked the config for that stage of the pipeline, and it also correctly shows the value of the `readable` environment variable to be `false`.  The `Buildspec` for that phase of the pipeline _should_ add `Readable` to `${FEATURESFILE}`, but I can't yet tell for definite whether it does.  There may be a logic error somewhere that assumes Readable _is_ meant to be deployed.

I am raising this issue in the meantime while I investigate it - other contributors may be aware of this and know the root cause, or may be able to assist me in diagnosing and resolving it more quickly.  I'm pretty sure it's not something I've done, but I'm not ruling that out!

Configuration Script generated from [installation page in docs](https://aws-samples.github.io/document-translation/docs/installation/) (run from CloudShell):
```
# ----------

# Configuration

# Source Service GitHub
export sourceGitService="github" # Set source service
export sourceGitRepo="mcalligator/document-translation" # Set repo name
export sourceGitBranch="main" # Set branch name

# Cognito Local Users
export cognitoLocalUsers="true" # Enable Cognito local users
export cognitoLocalUsersMfa="off" # Set MFA enforcement

# Web UI
export webUi="true" # Enable Web UI

# Translation
export translation="true" # Enable Translation
export translationLifecycleDefault="1" # Set default lifecycle

# ----------

# Deployment

# CDK Bootstrap
# cdk bootstrap aws://<redacted>/${AWS_REGION} # Bootstrap the account [commented out to enable re-running subsequent steps]

# Clone source code
git clone https://github.com/mcalligator/document-translation.git # Clone the upstream project git repository
cd document-translation # Change directory into the pulled project directory
git fetch --all --tags # Fetch available tags
git tag # View tags
git checkout tags/v2.3.0 # Checkout tag

# Push source code to your CodeCommit
git config --global credential.helper '!aws codecommit credential-helper $@' # Enable the AWS CLI git credentials helper
git config --global credential.UseHttpPath true # Enable the AWS CLI git credentials helper
git remote add codecommit https://git-codecommit.${AWS_REGION}.amazonaws.com/v1/repos/document-translation
# Add CodeCommit as a remote
git push codecommit main # Push files

# Deploy the pipeline
cd infrastructure # Change directory into the infrastructure directory
npm install # Install node dependencies
cdk deploy # Deploy
```

Output of log from last (failed) action in final stage of CodePipeline:
```
[Container] 2024/07/08 14:45:44.366875 Running command npm run build
> documenttranslation@0.1.0 build
> react-scripts build
Creating an optimized production build...
...

TypeError: Cannot set property mark of #<Object> which has only a getter
    at Object.connectTypeScriptPerformance (/codebuild/output/src27274233/src/website/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/profile/TypeScriptPerformance.js:12:36)
    at createTypeScriptReporter (/codebuild/output/src27274233/src/website/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:40:49)
    at Object.<anonymous> (/codebuild/output/src27274233/src/website/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:21:30)
    at Generator.next (<anonymous>)
    at /codebuild/output/src27274233/src/website/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/codebuild/output/src27274233/src/website/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:4:12)
    at /codebuild/output/src27274233/src/website/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:19:88
    at Object.<anonymous> (/codebuild/output/src27274233/src/website/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:23:38)
    at Generator.next (<anonymous>)
Failed to compile.
Module not found: Error: Can't resolve '../../../graphql/subscriptions' in '/codebuild/output/src27274233/src/website/src/page/readable/hooks'
[Container] 2024/07/08 14:45:57.892208 Command did not exit successfully npm run build exit status 1
[Container] 2024/07/08 14:45:57.896392 Phase complete: BUILD State: FAILED
[Container] 2024/07/08 14:45:57.896416 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run build. Reason: exit status 1
```

**Comment by philipws** [comment]
Hey @mcalligator thanks for reporting this. I've also had this reported elsewhere and the reporter has provided a fix for this which we will be adding upstream. 

This issue occurs when the subscriptions.ts file does not exist despite the function not being needed. A quick fix before the upstream is fixed is to add to the buildspec to create the subscriptions.ts file (a blank file).

Line 35 add `"touch subscriptions.ts",`

E.g.

```
        "~/.amplify/bin/amplify codegen",
        "touch subscriptions.ts",
        "cd ${WEBDIR_SRC}",
```

As the Translate feature creates "queries.ts", "mutations.ts" we don't see the error for those.

I'll update this ticket once upstream is resolved.

**Comment by philipws** [comment]
Hey @mcalligator this should now be resolved with https://github.com/aws-samples/document-translation/pull/68 . This will be in the next release.
