### ISSUE TITLE
Output  tab Missing "appHostedUrl"

### ISSUE THREAD

**Issue by teckgeekz** [aws-samples/document-translation#75]
Hi,
I have tried to deploy this app multiple times, Facing the same issue each time. Apphosted URL is missing.

I tried the latest version also tried installing older versions till v2.3.0.

However facing the same issue each time everything is deployed correctly. I am no coder hence need web UI,

If there is documentation for CLI i can try testing it however I would be grateful if you can help fix this issue.
![github issue](https://github.com/user-attachments/assets/6b0c7391-c28d-4ba1-92fd-83647d3c6121)

Application sucessfully installed and running :
![image](https://github.com/user-attachments/assets/5dde9a8e-ba4c-44a4-884d-f8e685f90a94)

**Comment by teckgeekz** [comment]
Hi thanks for responding, I think steps are missing on how to do that in the documentation. All I did was followed the installation wizard, each time I deployed the scrip I only got 2 stacks created but never got the app. As I stated earlier I am no coder. However if there are instructions I can definitely follow. As shown in the screenshot above I just get 2 stacks created. It would be helpful test how amazon translate works as currently I am using Microsoft one. Thanks for your response.

**Comment by philipws** [comment]
Hey @teckgeekz 

The installation workflow is currently being reworked. We depended on [AWS CodeCommit which is no longer accepting new customers](https://aws.amazon.com/blogs/devops/how-to-migrate-your-aws-codecommit-repository-to-another-git-provider/). So the install of this app needs to be refactored to accommodate that. 

For purely testing out the Amazon Translate service for quality you can use it within the console. The console is not targetted at non-tech users but it is the same back end that this app uses. https://console.aws.amazon.com/translate/home

**Comment by teckgeekz** [comment]
Thanks for answering, I will no longer try to deploy the app, was wondering if I am doing something wrong. I already tried the online interface however I does not support file size of more than 100 Kb, 

Thank you so much for you time and support.

**Comment by philipws** [comment]
Hi @teckgeekz no worries. I'll respond on here when the new install is ready in case you want to try it again.

The file size is limited for synchronous translations. For asynchronous (batch translation), which uses S3 as a source/target file storage, it can go far higher ([20MB](https://docs.aws.amazon.com/translate/latest/dg/what-is-limits.html)). This app uses asynchronous for that reason.
